import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/state/redux-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: "../public/fonts/satoshi.ttf",
  variable: "--font-satoshi",
});
const grotesk = localFont({
  src: "../public/fonts/bdo-grotesk.ttf",
  variable: "--font-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${grotesk.variable} ${poppins.variable} ${inter.variable} antialiased`}
      >
        <ReduxProvider>
          <main className="min-h-screen min-w-screen overflow-hidden">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
