import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/state/redux-provider";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const satoshi = localFont({
  src: "../public/fonts/satoshi.ttf",
  variable: "--font-satoshi",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"],
});
const grotesk = localFont({
  src: "../public/fonts/bdo-grotesk.ttf",
  variable: "--font-grotesk",
  display: "swap",
  preload: false,
  fallback: ["system-ui", "arial"],
});

export const amiamie = localFont({
  src: [
    {
      path: "../public/fonts/Amiamie-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-amiamie",
  display: "swap",
  preload: false,
  fallback: ["system-ui", "serif"],
});

export const amiamieRound = localFont({
  src: [
    {
      path: "../public/fonts/Amiamie-RegularRound.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-BlackRound.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-amiamie-round",
  display: "swap",
  preload: false,
  fallback: ["system-ui", "serif"],
});

export const metadata: Metadata = {
  title: "Nayanaka Creative Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${amiamie.variable} ${amiamieRound.variable} ${grotesk.variable} antialiased min-h-screen`}
      >
        <ReduxProvider>
          <Navigation />

          <main>{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
