import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/state/redux-provider";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

const satoshi = localFont({
  src: "../public/fonts/satoshi.ttf",
  variable: "--font-satoshi",
});
const grotesk = localFont({
  src: "../public/fonts/bdo-grotesk.ttf",
  variable: "--font-grotesk",
});

export const amiamie = localFont({
  src: [
    {
      path: "../public/fonts/Amiamie-Light.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-LightItalic.ttf",
      weight: "200",
      style: "italic",
    },

    {
      path: "../public/fonts/Amiamie-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-Italic.ttf",
      weight: "400",
      style: "italic",
    },

    {
      path: "../public/fonts/Amiamie-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-amiamie",
  display: "swap",
});

export const amiamieRound = localFont({
  src: [
    {
      path: "../public/fonts/Amiamie-RegularRound.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-ItalicRound.ttf",
      weight: "400",
      style: "italic",
    },

    {
      path: "../public/fonts/Amiamie-BlackRound.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Amiamie-BlackItalicRound.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-amiamie-round",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${amiamie.variable} ${amiamieRound.variable} ${grotesk.variable} antialiased min-h-screen`}
      >
        <ReduxProvider>
          <Navigation />

          <main>{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
